KhronosGroup/COLLADA2GLTF

GLTF/src/GLTFMaterial.cpp
Literally a one line fix. This was creating an issue for a material replacement system for a pipeline. Figured I'd point out this simple fix.
=> Fix missing names for materials

GLTF/include/GLTFAsset.h, GLTF/src/GLTFAccessor.cpp, GLTF/src/GLTFAsset.cpp, src/main.cpp
For #49. Element aggregators return vectors instead of sets. This is confirmed to produce the same element ordering between runs.
=> Make element ordering deterministic

src/main.cpp
All GLB chunks must be padded to 4-byte boundaries:
https://github.com/KhronosGroup/glTF/blob/2.0/specification/2.0/GLB_FORMAT.md#chunks
=>  Write padding for all chunks

.appveyor.yml, CMakeLists.txt
Closes #54.
Cuts Appveyor build time from 26 minutes to ~8. 
This is only for Appveyor (Windows builds), and only on 2.0. I do not currently plan to try to hack this into the 1.0 cmake build.
This will also get added to the Travis build likely when I'm adding Mac OS build support.
=> Added precompiled option to accelerate appveyor build

include/COLLADA2GLTFWriter.h, src/COLLADA2GLTFWriter.cpp
=> Check quaternion decomposition direction for axis angle

GLTF/CMakeLists.txt
Removes redundant c++11 flag and properly sets the standard in GLTF cmakelists. 
There are quite a few draco targets. This puts them in a folder so they don't clutter up the Visual Studio solution for Windows developers.
=> CMake cleanup

GLTF/src/GLTFAccessor.cpp
According to the glTF-Validator, when there is no `bufferView` in `accessor`, the `byteOffset` should be omitted as well.
=> Removed byteOffset in accessors when there is no bufferView

README.md
Visual Studio link should point to Visual Studio,
not Visual Studio Code.
=> correct Visual Studio link

GLTF/include/GLTFAsset.h, GLTF/src/GLTFAsset.cpp, src/main.cpp
Fixes #66.
Related:
- https://github.com/KhronosGroup/glTF-Sample-Models/issues/108
- https://github.com/KhronosGroup/glTF/issues/1052
Disclaimer: I have no idea how memory management works in C++. Do i need to deallocate the old
animations somehow? 😅
=> Merge animations before writing to JSON.

GLTF/src/GLTFAsset.cpp
The `emissiveTexture` didn't get its `id` assigned, because it was not registered in the `textures` vector.
=> Fixed PBR material not registering emissiveTexture

GLTF/include/GLTFMaterial.h, GLTF/src/GLTFMaterial.cpp
The PBR texture `scale` was an `int`, but according to the spec, it should be `float`.
Also, the default scale of `1` is not written to the output JSON.
=> PBR Texture scale is now a float

GLTF/src/GLTFImage.cpp
Some image types, `.tga` in this case, allow the file to be started with `null` characters.
When creating an `std::string` from such a string, the `std::string` created assumes the first `null` character as the terminator, causing the size to be 0. This won't throw an exception, but its not the desired behavior in this case.
However, when creating an `std::string` from such a string with start and offset (existing code), the constructor believes that indices provided are out of bounds and throws an exception.
The way to fix this is to first create a string with a defined size, overriding the null character check. Then a substring can be created from this string.
Here is some standalone sample code to demonstrate this:
```
#include <iostream>
#include <stdexcept>
void foo(const char *bar, …
```
=> Fix for image byte string that starts with null character

GLTF/include/GLTFImage.h, GLTF/src/GLTFImage.cpp
In my Maya2glTF exporter, I had crashes when running the exporter twice, because the global GLTF image cache still contained destructed images. 
This PR should fix that, it adds private constructors that remember the `cacheKey`, the destructor uses this key to remove from the cache.
=> Images are now removed from cache when destructed

GLTF/include/GLTFMaterial.h, GLTF/include/GLTFOptions.h, GLTF/src/GLTFAsset.cpp, GLTF/src/GLTFMaterial.cpp, include/COLLADA2GLTFExtrasHandler.h, src/COLLADA2GLTFExtrasHandler.cpp, src/COLLADA2GLTFWriter.cpp, src/main.cpp
Changes to allow double-sided common materials to be specified both from command line and within the COLLADA file.
This is used to correctly display fault planes in geological models.
=> Double sided materials

CHANGES.md
For #178.
The CMake build for 1.3.0 is currently broken: https://github.com/google/draco/issues/372
=> Upgrade to Draco 1.2.5

CHANGES.md, GLTF/src/GLTFAsset.cpp
Digging through some old issues: this fixes #76.
Surprised this hasn't come up again; I guess there aren't a lot of COLLADA models with bump maps.
=> Fix issues with exporting normal maps

src/COLLADA2GLTFWriter.cpp
Solved issue #185 by normalizing bone weights vector.
=> Normalize bone weights #185

.appveyor.yml, CHANGES.md
As per [Microsoft](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-6.0/aa260978(v=vs.60)#a-list-of-redistributable-files)
> Note that debug versions of an application are not redistributable
This seems to be a legal restriction, not necessarily a technical one. However, I'd rather err on the side of caution, plus this will make our Appveyor builds about twice as fast.
=> Remove debug builds from CI

.appveyor.yml, COLLADA2GLTFWriter.cpp
This is a fix for 1.0 branch
Previously we would process the `visual_scene` hierarchy and once that was done we'd iterate over `library_nodes` and resolve any `instance_node` references that needed to be resolved.
The problem is when a `instance_node` is within the `library_nodes` hierarchy, these references are never resolved, so we end up with a glTF that can have meshes that are never reachable from the root node, so therefore never rendered.
This change essentially just moved the existing code to within `writeNode`. Now whenever a node is encountered regardless of where it is located, it resolves any previously encountered `instance_node` references to itself.
=> We now properly handle instance_node that comes before the node within library_nodes

src/COLLADA2GLTFExtrasHandler.cpp, src/COLLADA2GLTFWriter.cpp
- Some models in the wild had `double_sided` tags that had `true` instead of `1`
- If a `transparent` color was specified we were using `OpaqueMode` of `RGB_ONE` which isn't even the default. You can see the formulas in the 1.4.1 and 1.5.0 specs in Chapter 7 under `Determining Transparency (Opacity)`. Note that 1.4.1 doesn't have `A_ZERO` or `RGB_ONE`, they were added in 1.5.0.
=> Tweaks to lighting and support for double sided models found in the wild

.gitmodules, CHANGES.md, GLTF/include/GLTFAsset.h, GLTF/src/GLTFAsset.cpp, include/COLLADA2GLTFWriter.h, src/COLLADA2GLTFWriter.cpp, src/main.cpp, test/src/COLLADA2GLTFWriterTest.cpp
Depends on https://github.com/KhronosGroup/OpenCOLLADA/pull/607
=> Animation groups

CHANGES.md, CMakeLists.txt, GLTF/CMakeLists.txt, GLTF/include/GLTFAnimation.h, GLTF/include/GLTFAsset.h, GLTF/include/GLTFBuffer.h, GLTF/include/GLTFMaterial.h, GLTF/include/GLTFNode.h, GLTF/include/GLTFObject.h, GLTF/include/GLTFPrimitive.h, GLTF/include/GLTFTechnique.h, GLTF/src/GLTFAnimation.cpp, GLTF/src/GLTFAsset.cpp, GLTF/src/GLTFBuffer.cpp, GLTF/src/GLTFImage.cpp, GLTF/src/GLTFMaterial.cpp, GLTF/src/GLTFNode.cpp, GLTF/src/GLTFObject.cpp, GLTF/src/GLTFPrimitive.cpp, GLTF/src/GLTFTechnique.cpp, dependencies/OpenCOLLADA/modules/COLLADASaxFrameworkLoader/CMakeLists.txt, dependencies/OpenCOLLADA/modules/COLLADASaxFrameworkLoader/COLLADAFramework/COLLADABaseUtils/CMakeLists.txt, dependencies/OpenCOLLADA/modules/COLLADASaxFrameworkLoader/GeneratedSaxParser/CMakeLists.txt, src/COLLADA2GLTFWriter.cpp
I tried to keep it as simple as possible. This has a few changes
1. `~Asset` now cleans up all of the top level objects. I believe I do it in the correct order.
2. All the secondary objects get deleted with its parent (eg. `Animation::Channel`, `Primitive::Target`, etc)
3. Since we are cleaning up the data pointers for `Image` and `Buffer`, I made them use the `malloc`/`realloc`/`free` everywhere. It was like that most places but there were a few `new unsigned char[]`'s which isn't recommended (although with a byte array was probably fine). I went this way strictly because I had to change less code, so maybe we want to clean that up with a more modern technique at some point.
4. I ran into a bunch of models that didn't have lights/cameras but had instances of them. It looks like the Modo …
=> Frees memory when an asset goes away

GLTF/src/GLTFAsset.cpp
Looks like there was a typo when getting unique animation accessors and the same merged animation was being pushed on the vector multiple times. These both caused duplicate deletions.
=> Fixed accidental duplicate deletion

CHANGES.md, GLTF/include/GLTFNode.h, GLTF/src/GLTFNode.cpp, src/COLLADA2GLTFWriter.cpp, test/src/COLLADA2GLTFWriterTest.cpp
All the other members of a node are references that are cleaned up later in `~Asset` except for the `transform`. If we clone a node, then the transform will be deleted twice. This clones the transform to prevent that.
=> Need to clone transforms because they are owned by a node

include/COLLADA2GLTFExtrasHandler.h, src/COLLADA2GLTFExtrasHandler.cpp, src/COLLADA2GLTFWriter.cpp
Fixes the segmentation fault for multiple materials and normal maps (see issue #249) 
- Using map of effect id to bump texture instead of only saving last bump
texture
=> Fixes normal map segmentation fault

GLTF/include/GLTFNode.h, GLTF/src/GLTFNode.cpp, include/COLLADA2GLTFWriter.h, src/COLLADA2GLTFWriter.cpp, test/src/COLLADA2GLTFWriterTest.cpp
If you have a model that is laid out like this
```xml
<library_visual_scenes>
<visual_scene id="ID1">
<node id="ID2a">
<instance_node url="#ID3" />
</node>
<node id="ID2b">
<instance_node url="#ID3" />
</node>
</visual_scene>
</library_visual_scenes>
<library_nodes>
<node id="ID3">
<node id="ID4">
<node id="ID5">
<node id="ID6">
<node id="ID7" name="instance_1">
<instance_node url="#ID8" />
</node>
</node>
</node>
</node>
</node>
<node id="ID8">
</node>
</library_nodes>
```
`ID2a` and `ID2b` ends up as targets for `ID3`.
`ID3` is found and traversed and `ID7` ends up as the target for `ID8`
Then `ID3` is cloned twice and added as the child for `ID2a` and `ID2b`.
When `ID8` is found, its added as the child of the original `ID7`, but not the cloned versions of `ID7` that are part of the …
=> Fixed issues where there were multiple levels of instances

CHANGES.md, GLTF/src/GLTFAsset.cpp
Fixes #251
For [struct.dae.zip](https://github.com/KhronosGroup/COLLADA2GLTF/files/3693870/struct.dae.zip) this now produces 6 materials instead of 12.
For [test.dae.and.gltf.zip](https://github.com/KhronosGroup/COLLADA2GLTF/files/3325471/test.dae.and.gltf.zip) this now produces 21 materials instead of hundreds.
=> De-duplicate GLTF generated materials
