README.md
=> Add building info

CMakeLists.txt
make sure to update submodules recursively before building this
=> updated openCOLLADA to v1.6.39 from 1.6.0

GLTF/GLTFAsset.cpp
=> Fix unbound skin and material

GLTF/GLTFAnimation.cpp
don't let index+1 go to array size
=>  Fix/out of bound animation

COLLADA2GLTFWriter.cpp, GLTF/GLTFAsset.cpp
Fixes #25, frees up #21 for review
=> Fix material instancing

.gitmodules
otherwise git clone --recursive does not work for anonymous user
=> fix modules to use https

.gitmodules, CMakeLists.txt
From feedback in #37. Makes master compatible with switching into the 2.0 branch.
=> Move open collada

.travis.yml, appveyor.yml
Switch tokens for KhronosGroup tokens
Change git push URL to Khronosgroup
=> Updated tokens

GLTF/src/GLTFMaterial.cpp
=> Write out glossinessFactor to a scalar; default converted materials to

GLTF/include/GLTFAsset.h, GLTF/src/GLTFAsset.cpp, src/main.cpp
=> Optimize out light nodes when exporting PBR

GLTF/include/GLTFAsset.h, GLTF/src/GLTFAsset.cpp, GLTF/src/GLTFMaterial.cpp
Changes for https://github.com/KhronosGroup/glTF-Sample-Models/pull/76
=> Misc cleanup

GLTF/include/GLTFNode.h, GLTF/src/GLTFNode.cpp, src/COLLADA2GLTFWriter.cpp
The bind shape matrix has to be postmultiplied
with the inverse bind matrices.
=> Fix for bind shape matrix handling

src/COLLADA2GLTFWriter.cpp
do not choke on path with uuencoded special characters
=> mixed up uri for path fix

GLTF/include/GLTFNode.h, GLTF/src/GLTFMesh.cpp, GLTF/src/GLTFNode.cpp, GLTF/src/GLTFPrimitive.cpp, include/COLLADA2GLTFWriter.h, src/COLLADA2GLTFWriter.cpp
=> Fix node instancing

CHANGES.md, GLTF/src/GLTFImage.cpp
=> Fix png detection and strip period from extension for mime types

GLTF/include/GLTFAnimation.h, GLTF/include/GLTFAsset.h, GLTF/include/GLTFMesh.h, GLTF/include/GLTFPrimitive.h, GLTF/src/GLTFAnimation.cpp, GLTF/src/GLTFAsset.cpp, GLTF/src/GLTFMesh.cpp, GLTF/src/GLTFPrimitive.cpp
Maya2glTF exports blend shapes now. I had to add support to the GLTF module for doing this.
PS: I'm not sure if I handle the draco compression correctly yet, I haven't test this yet.
=> Added support for blend shapes in GLTF module

CHANGES.md, src/COLLADA2GLTFWriter.cpp
=> Don't make textures if there is no image backing it

.appveyor.yml, .gitmodules
I believe that this is what is currently breaking the appveyor build.
=> Added missing .git extensions

.travis.yml, CHANGES.md, src/COLLADA2GLTFWriter.cpp, src/main.cpp
=> Fixed issues with path parsing on windows

CHANGES.md, GLTF/CMakeLists.txt, GLTF/include/GLTFMaterial.h, GLTF/src/GLTFAsset.cpp, GLTF/src/GLTFMaterial.cpp, GLTF/test/include/GLTFAssetTest.h, GLTF/test/src/GLTFAssetTest.cpp, include/COLLADA2GLTFWriter.h, src/COLLADA2GLTFWriter.cpp
For #169. Should work, but needs some unit tests.
=> Add support for multiple maps

CHANGES.md, GLTF/include/GLTFAccessor.h, GLTF/src/GLTFAccessor.cpp, GLTF/src/GLTFNode.cpp, include/COLLADA2GLTFWriter.h, src/COLLADA2GLTFWriter.cpp
=> Initial support for morph targets

CHANGES.md, GLTF/src/GLTFMaterial.cpp, include/COLLADA2GLTFOptions.h, src/COLLADA2GLTFWriter.cpp
=> Support transparent colors

GLTF/include/GLTFOptions.h, src/main.cpp
Add command line option to preserve unused semantics.
=> Add preserveUnusedSemantics option.

CHANGES.md, GLTF/src/GLTFAsset.cpp
=> Fix memory-management error for GLTF 1.0 materials
